language: php

php:
  - 7.3

before_script:
  - composer install --dev

script: ./vendor/bin/simple-phpunit

notifications:
    email:
        - josecarlosduran@gmail.com
    slack: tobalinaconsulting:sdhe9T5bw5qW9PpRs7Q3at9a
